#serverless.yml
org: ivoveliz
app: test
service: serverless-flask-container

provider:
  provider:
  name: aws
  region: us-west-2
  ecr:
    images:
      appimage:
        path: ./

functions:
  app:
    image:
      name: appimage
    timeout: 30
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'